# Generated by Django 5.0 on 2023-12-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the post', max_length=100)),
                ('body', models.TextField(help_text='Body of the post', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this post was last updated')),
                ('poster', models.ForeignKey(help_text='Who posted it', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
